// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uhckxdecaonwhxkjdqxu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVoY2t4ZGVjYW9ud2h4a2pkcXh1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5ODYwMzQsImV4cCI6MjA3MDU2MjAzNH0.09HQ0BDTDimiqiVCexZ5Fb86IajpaOlVBjSe7YwX4tQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});